### ISSUE TITLE
Arcade Floor Concept Art

### ISSUE THREAD

**Issue by gold-mari** [GDACollab/Asterion#19]
We need concept art for the floor! Give it please!!!!!
We want 3.

- [ ]  Concept 1
- [ ]  Concept 2
- [ ]  Concept 3

**Comment by gold-mari** [comment]
Hi this is Dylan I did some concept art for the floor, take a look:

![Image](https://user-images.githubusercontent.com/62458416/212794433-99ddc281-4db8-4b81-938a-9a8467065f28.png)

How is that

**Comment by gold-mari** [comment]
# This is bad!!! Do better!!!

**Comment by ambiguousname** [comment]
#12

**Comment by gold-mari** [comment]
apologies tyler, this issue has been closed since we have the final asset! see: #23
